learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('control/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import static

# from . import settings_common, settings_dev

app_name = 'learning_logs'
urlpatterns = [
	path('', views.index, name='index'),
	# path('', views.IndexView.as_view(), name='index'),
	#全てのトピックを表示する
	path('topic/', views.topic, name='topic'),
	#個別トピックの詳細ページ
	path('topic/<int:topic_id>/', views.topic_child, name='topic_child'),
	#新しいトピック作成ページ
	path('new_topic/', views.new_topic, name='new_topic'),
	#新しい記事作成ページ
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	#ユーザーが追加した記事(entry)の編集ページ
	path('edit/<int:entry_id>/', views.edit, name='edit'),
	#about
	path('about/', views.about, name='about'),
	#contact
	path('contact/', views.contact, name='contact'),
	# 問い合わせ
	path('inquiry/', views.InquiryView.as_view(),name="inquiry"),
]

# 開発サーバーでメディアを配信可能にする設定
# urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

users/urls.py
"""users用URLパターン定義"""

from django.urls import path, include
from . import views

# Create your views here.
app_name = 'users'

urlpatterns = [
	#デフォルトの認証URLを取り込む
	path('', include('django.contrib.auth.urls')),
	#ユーザー登録ページ
	path('register/', views.register, name='register'),
	#ユーザーの記事一覧ページ
	path('entries/<int:user_id>/', views.user_entries, name='user_entries'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)#add

	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		return str(self.topic) + f": {self.text[:25]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry
from django.core.mail import EmailMessage

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''} #ラベルを生成しない指示

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols':80})}

class InquiryForm(forms.Form):
	name = forms.CharField(label='お名前', max_length=30)
	email = forms.EmailField(label='メールアドレス')
	title = forms.CharField(label='タイトル',max_length=30)
	message = forms.CharField(label='メッセージ',widget=forms.Textarea)

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['name'].widget.attrs['class'] = 'form-control col-9'
		self.fields['name'].widget.attrs['placeholder'] = 'お名前'
		self.fields['email'].widget.attrs['class'] = 'form-control col-11'
		self.fields['email'].widget.attrs['placeholder'] = 'メールアドレス'
		self.fields['title'].widget.attrs['class'] = 'form-control col-11'
		self.fields['title'].widget.attrs['placeholder'] = 'タイトル'
		self.fields['message'].widget.attrs['class'] = 'form-control col-12'
		self.fields['message'].widget.attrs['placeholder'] = '問い合わせ内容をここに入力してください'

	def send_email(self):
		name = self.cleaned_data['name']
		email = self.cleaned_data['email']
		title = self.cleaned_data['email']
		message = self.cleaned_data['message']

		subject = 'お問い合わせ{}'.format(title)
		message = '送信者名：{0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
		from_email = 'aaa@aaa.com'
		to_list = [#問い合わせメールの宛先一覧(to)
			'test@example.ccom'
		]
		cc_list = [#問い合わせメールの宛先一覧(cc)
			email
		]

		message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list) #EmailMessageインスタンス生成
		message.send() #メール送信

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import TopicForm, EntryForm, InquiryForm
from django.http import Http404
from django.views import generic #クラスベースビュー
from django.urls import reverse_lazy
from django.contrib import messages
import logging
import logging.handlers

logger = logging.getLogger(__name__) #forms.pyに記述するメール送信メソッド呼び出し


# Create your views here.
def index(request):
	return render(request, 'learning_logs/index.html')

# class IndexView(generic.TemplateView):
# 	template_name = 'index.html'

def about(request):
	return render(request, 'learning_logs/about.html')

def contact(request):
	return render(request, 'learning_logs/contact.html')

def topic(request):
	topics = Topic.objects.order_by('date_added')
	context = {'topic': topics}
	return render(request, 'learning_logs/topic.html', context)

# class TopicView(generic.ListView):
# 	model = Topic
# 	template_name = 'topic.html'
#	paginate_by = 2
	
# 	def get_queryset(self):
# 		topics = Topic.objects.order_by('date_added')

class InquiryView(generic.FormView):
	template_name = 'inquiry.html'
	form_class = InquiryForm
	success_url = reverse_lazy('learning_logs:inquiry')

	def form_valid(self, form):
		form.send_email()
		messages.success(self.request, 'メッセージを送信しました。') #メッセージ表示
		logger.info('inquiry sent by {}'.format(form.cleaned_data['name']))
		return super().form_valid(form)

def topic_child(request, topic_id):
	"""１つのトピックとそれについての全ての記事を表示"""
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, "learning_logs/topic_child.html", context)

@login_required
def new_topic(request):
	if request.method != 'POST':#データ送信されていない時
		form = TopicForm()#空のフォーム
	else:#データ送信された時
		form = TopicForm(data=request.POST)#データ入りフォーム
		if form.is_valid():#バリデーション
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()#保存
			return redirect('learning_logs:topic')#保存後の画面表示先
	context = {'form': form}#フォームを送る
	return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.owner = request.user
			new_entry.save()
			return redirect('learning_logs:topic_child', topic_id=topic_id)
	context = {'topic': topic,'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit(request, entry_id):
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	# トピックが現在のユーザーが所持するものであることを確認する
	if entry.owner != request.user:
		raise Http404

	if request.method != 'POST':
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid:
			form.save()
			return redirect('learning_logs:topic_child', topic_id=topic.id)

	context = {'entry': entry, 'topic':topic ,'form':form}
	return render(request, 'learning_logs/edit.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.contrib.auth.models import User

# Create your views here.
def register(request):
	"""新しいユーザーを追加する"""
	if request.method != 'POST':
		form = UserCreationForm() #空のユーザーフォーム
	else:
		form = UserCreationForm(data=request.POST) #入力済フォーム
		if form.is_valid():
			new_user = form.save()
			login(request, new_user)
			return redirect('learning_logs:index')
	context = {'form':form}
	return render(request, 'registration/register.html', context)

def user_entries(request, user_id):
	"""ユーザーの全ての記事(entry)を表示"""
	user = User.objects.get(id=user_id)
	entries = user.entry_set.order_by('-date_added')
	context = {'entries': entries}
	return render(request, 'users/user_entries.html', context)

learning_logs/templates/inquiry.html
{% extends "learning_logs/base.html" %}

{% block title %}お問い合わせ｜notopi{% endblock %}

{% block page_header %}
	<h2>Contact</h2>
{% endblock page_header %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="my-div-style">
			<form method="post">
				{% csrf_token %}

				{{ form.non_field_errors }}

				{% for field in form %}
				<div class="group row">
					<label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
						<strong>{{ field.label_tag }}</strong>
					</label>
					<div class="col-sm-8">
						{{ field }}
						{{ field.errors }}
					</div>
				</div>
				{% endfor %}

				<div class="offset-sm-4 col-sm-8">
					<button class="btn btn-primary" type="submit">送信</button>
				</div>
			</form>
		</div>
	</div>
</div>

<!-- <section>
	<div>
		<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeLTAcdk7t-poEjcp5rJ6QRrDi51-oUcWpKxQZDi_yUboA2YQ/viewform?embedded=true" width="640" height="673" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>
	</div>
</section> -->

{% endblock content%}

learning_logs/templates/learning_logs/about.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class="jumbotron">
	<h1 class="display-4">notopiの説明</h1>
	
	<p class="lead"><br>
		記事の書き込み・閲覧ができる掲示板です。<br>
		アカウントを作成すれば、誰でもトピックを立てて記録できます。<br>
		<br>
		<strong><b>使い方</b></strong><br>
		新しく学んだこと・趣味・習い事等々・・・好きなトピックについて記録できます。<br>
		具体的で分かりやすいトピック名は、他の人が見つけやすいです。<br>
		<br>
		<strong><b>特徴</b></strong><br>
		他の人のトピックに投稿できます。<br>
		自分の記事をまとめて表示できます。<br>
		<br>
		<strong><b>注意</b></strong><br>
		ユーザー名が表示名になります。<br>
		登録時のユーザー名・パスワードは<b><strong>メモ</strong></b>しましょう。<br>
		忘れると、再登録になるのです。。<br>
	</p>
	
	{% if not user.is_authenticated %}
	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
		role="button">使ってみる &raquo;</a>
	{% else %}
	<a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topic' %}">新しいトピックをつくる &raquo;</a>
	{% endif %}
</div>

{% endblock content%}

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>

	<!-- Bootstrap css -->
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

	<!-- mystyle css -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css'%}">
	{% block head %}{% endblock %}
</head>

<body>
	<div id="wrapper">
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

		<a class="navbar-brand" href="{% url 'learning_logs:index'%}">notopi</a>
	
		<!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button> -->
		<div class="collapse show navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
			<a class="nav-link" href="{% url 'learning_logs:topic'%}">トピック一覧</a></li>
		</ul>
		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'learning_logs:inquiry' %}">問い合わせ</a>
			</li>
			{% if user.is_authenticated %}
			<li class="nav-item">
				<span class="navbar-text">こんにちは {{ user.username }}さん</span>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:logout' %}">ログアウト</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:register' %}">ユーザー登録</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'users:login' %}">ログイン</a></li>
			{% endif %}
		</ul>
		</div>
		
	</nav>
	
	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottom">
		{% block page_header %}{% endblock page_header %}
		</div>

		{% if messages %}
		<div class="container">
			<div class="row">
				<div class="my-div-style w-100">
					<ul class="messages" style="list-style: none;">
						{% for message in messages %}
						<li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
							{{ message }}
						</li>
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
		{% endif %}

		<div>
		{% block content %}{% endblock content %}
		</div>
	</main>

	<!-- footer -->
	<footer>
		<div class="container">
			<p class="m-0 text-center small">Copyright &copy; notopi 2021</p>
		</div>
	</footer>

{% block script %}{% endblock script %}
</div>
</body>

</html>

learning_logs/templates/learning_logs/delete.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p><a href="">{{topic}}</a></p>
<p>記事を編集:</p>

<form action="{% url 'learning_logs:delete' entry_id %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>削除する</button>
</form>
{% endblock content%}

learning_logs/templates/learning_logs/edit.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p><a href="{% url 'learning_logs:topic_child' topic.id %}">{{topic}}</a></p>
<p>記事を編集:</p>

<form action="{% url 'learning_logs:edit' entry.id %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>記事を更新</button>
</form>
{% endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class="jumbotron">
	<h1 class="display-4">記録しよう</h1>
	
	<p class="lead">トピックを作成して、いつでも振り返ろう。<br>
		趣味・習い事・ハマっていること等々・・・<br><br>
		立てたトピックについて、新しいことを学んだら、その内容をまとめた記事を書こう。<br>
		他の人のトピックにも投稿できます。
	</p>
	
	<a href="{% url 'learning_logs:about' %}">more...</a><br>
	<br>
	{% if not user.is_authenticated %}
	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
		role="button">使ってみる &raquo;</a>
	{% else %}
	<a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topic' %}">新しいトピックをつくる &raquo;</a>
	{% endif %}
</div>

{% endblock content%}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p><a href="{% url 'learning_logs:topic_child' topic.id %}">{{ topic }}</a></p>

<p>新しい記事:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>追加する</button>
</form>
{% endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>新規トピックを追加:</p>

<form action="{% url 'learning_logs:new_topic' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>トピックを追加</button>
</form>
{% endblock content%}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
	<h2>トピック</h2>
{% endblock page_header %}

{% block content %}
	<ul>
		{% for t in topic %}
			<li>
				<a href="{% url 'learning_logs:topic_child' t.id %}">{{t}}　<span>（{{ t.owner }}）</span></a>
			</li>
		{% empty %}
			<li>トピックはまだ作成されていません。</li>
		{% endfor %}
	</ul>
	<a href="{% url 'learning_logs:new_topic' %}">新しいトピックを作成</a>
{% endblock content%}

learning_logs/templates/learning_logs/topic_child.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
	<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">新しい記事を追加</a>
	</p>

	{% for entry in entries %}
	<div class="card mb-3">
		<h5 class="card-header">
			<p>{{ entry.date_added|date:'Y年m月d日 H:i' }} （<a href="{% url 'users:user_entries' entry.owner.id %}">{{entry.owner}}</a>）</p>
			{% if request.user == entry.owner %}
			<small><a class="text-secondary" href="{% url 'learning_logs:edit' entry.id %}">記事を編集</a></small>
			{% endif %}
		</h5>
		<div class="card-body">{{ entry.text|linebreaks }}</div>
	</div>
	{% empty %}
		<p>このトピックにはまだ記事がありません。</p>
	{% endfor %}
	
{% endblock content%}

users/templates/users/user_entries.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
	<h3></h3>
{% endblock page_header %}

{% block content %}
	{% for entry in entries %}
	<p><a href="{% url 'learning_logs:topic_child' entry.topic.id %}">{{entry.topic}}</a></p>
	<div class="card mb-3">
		<h5 class="card-header">
			<p>{{ entry.date_added|date:'Y年m月d日 H:i' }} （{{entry.owner}}</a>）</p>
		</h5>
		<div class="card-body">{{ entry.text|linebreaks }}</div>
	</div>
	{% empty %}
		<p>まだ記事がありません。</p>
	{% endfor %}
	
{% endblock content%}